apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-replicaset
  labels:
    app: mysql
    component: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      component: db
  template:
    metadata:
      labels:
        app: mysql
        component: db
    spec:
      containers:
        - name: my-db
          image: 456965715091.dkr.ecr.us-east-1.amazonaws.com/my-db:latest
          imagePullPolicy: Always 
          ports:
          - containerPort: 3306
            protocol: TCP
          env:    
            - name: DBHOST
              value: "my-db"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              value: "pw"
            - name: APP_COLOR
              value: "blue"
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: ecr-credentials