apiVersion: v1
kind: Pod
metadata:
  name: my-app
labels:
  env: prod
spec:
  containers:
    - name: my-db
      image: 456965715091.dkr.ecr.us-east-1.amazonaws.com/my-db:latest
      imagePullPolicy: Always 
      ports:
      - containerPort: 3306
        protocol: TCP

        